#!/bin/sh /etc/rc.common
# Copyright (c) 20022 Zcoder

START=99
USE_PROCD=1

screen_file="/var/log/ngrok.log" 
screen_name="ngrok"
CONFIG_PATH="/root/.config/ngrok/ngrok.yml"

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
   echo "NGROK PORT FORWARDING [ ENABLE ]"
	[ $enabled -gt 0 ]
}


start_service() {
    if screen -list | grep -q "$screen_name"; then
        echo "Session already exists.. "
        screen -S $screen_name -X quit
        echo "Screen exited.."
    fi

    if [ -f "$screen_file" ]; then
        rm $screen_file 
        echo "Delete screen $screen_file.." 
    fi
    screen -dmS $screen_name -L -Logfile $screen_file ngrok start --all  --config=$CONFIG_PATH
    echo  "NGROK SERVICE RUNING...."
}

stop_service() {
   if [ -f "$screen_file" ]; then
        rm $screen_file 
        echo "Delete screen $screen_file.." 
    fi
    screen -S $screen_name -X quit
    echo  "NGROK service terminate...."
   
}


reload_service() {
	stop
	start
}
